# wrangler.toml
name = "stripe-worker"
compatibility_date = "2024-01-01"

[vars]
STRIPE_PUBLIC_KEY = "mk_1SoE4yByRBDz27UP8Gj1DkSr"
STRIPE_SECRET_KEY = "mk_1SoE5gByRBDz27UPt54qrdxF"

[env.production.vars]
STRIPE_PUBLIC_KEY = "mk_1SoE4yByRBDz27UP8Gj1DkSr"
STRIPE_SECRET_KEY = "mk_1SoE5gByRBDz27UPt54qrdxF"
